### ISSUE TITLE
Instructions vs Code Mismatch

### ISSUE THREAD

**Issue by iduaum** [xinthose/Netplan-GUI#1]
Not sure what's wrong here but code isn't working as expected with Internal Server Error code 500 to the rest.py 8080/get_interfaces1 endpoint.

**Comment by xinthose** [comment]
Oops.  `SERVER` should have been `localhost` in the service file.  Thank you.
https://github.com/xinthose/Netplan-GUI/commit/f6ede470f3c96d82200ae65be77f19108210d0da
