### ISSUE TITLE
Add VLAN interfaces 

### ISSUE THREAD

**Issue by kirush0280** [xinthose/Netplan-GUI#10]
Please add features to add vlan interfaces

**Comment by xinthose** [comment]
Do you have an example netplan yaml file I can look at?

**Comment by kirush0280** [comment]
[enp9s0.txt](https://github.com/xinthose/Netplan-GUI/files/9462089/enp9s0.txt)

**Comment by xinthose** [comment]
Thank you.  I think this would be not that hard to add.  I do not use VLAN's myself personally.  How do you come up with the number after `vlan`?  (e.g. `vlan1300`, `vlan4094`, etc.).  Do you just make up a unique number?  The `id` should match the number in the interface name correct?

**Comment by kirush0280** [comment]
Yes VLAN Interface has 2 parameters VLAN name & VLAN ID and Ip/mask and so on..

It is more convenient for me when the name and id are the same, but this is not necessary.
But fields must be: VLAN NAME & ID

**Comment by xinthose** [comment]
@kirush0280 Hello.  I'm sorry, I did work on this and created a [dynamic branch](https://github.com/xinthose/Netplan-GUI/tree/dynamic).  It would be too much work though and I've lost interest in doing it.
