### ISSUE TITLE
Can't start 

### ISSUE THREAD

**Issue by kirush0280** [xinthose/Netplan-GUI#9]
Can't start netplan-gui-rest   
[netplan-gui-rest-error.log](https://github.com/xinthose/Netplan-GUI/files/9452684/netplan-gui-rest-error.log)

**Comment by xinthose** [comment]
It's because you're using python 3.8 instead of 3.9, which uses `List` instead of `list`.  I should update the code to be backwards compatible.  Thank you for pointing this out to me.  I only learned this recently myself.

**Comment by kirush0280** [comment]
I upgraded to python 3.9, and upgraded modules. Now i stopped at this moment.
[netplan-gui-rest-error.log](https://github.com/xinthose/Netplan-GUI/files/9459054/netplan-gui-rest-error.log)

**Comment by xinthose** [comment]
fixed in [v1.0.4](https://github.com/xinthose/Netplan-GUI/releases/tag/v1.0.4 )
